# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=8, verbose_name='匹配的性别'),
        ),
    ]
